### get by Email
GET localhost:8080/email_history/get_by_email
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzMxNTQ1NzEsInVzZXJuYW1lIjoibXlsYXB0b3AwNjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjczMjQwOTcxLCJpc3MiOiJZb3VUdWJlIHRlc3QgcG9ydGFsaSJ9.B3AML0wv8vYqIK0wYDibhhFWXtMChei7oqs7oQBLb51Yz-fvUlmKhwYFBpNFbvtDtEAuUyszruayCWOKot37xg
Content-Type: application/json

{
  "email": "mydream7usa@gmail.com"
}

### get by date
GET localhost:8080/email_history/date/2023-01-07
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzMxNTQ1NzEsInVzZXJuYW1lIjoibXlsYXB0b3AwNjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjczMjQwOTcxLCJpc3MiOiJZb3VUdWJlIHRlc3QgcG9ydGFsaSJ9.B3AML0wv8vYqIK0wYDibhhFWXtMChei7oqs7oQBLb51Yz-fvUlmKhwYFBpNFbvtDtEAuUyszruayCWOKot37xg

### get list
GET localhost:8080/email_history/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzMxNTQ1NzEsInVzZXJuYW1lIjoibXlsYXB0b3AwNjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjczMjQwOTcxLCJpc3MiOiJZb3VUdWJlIHRlc3QgcG9ydGFsaSJ9.B3AML0wv8vYqIK0wYDibhhFWXtMChei7oqs7oQBLb51Yz-fvUlmKhwYFBpNFbvtDtEAuUyszruayCWOKot37xg


