GET Localhost:7070/report/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE5MDA2OTcsInVzZXJuYW1lIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MTk4NzA5NywiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.jncnYlwUMSuC_NHE9g-5zoWTpcds7IoRwLgIQEcOIzxCgE4sw21QK3NsAssttEEYfMyEcK4N1tQBHpmGqf2oVg

### POST
POST Localhost:7070/report/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE5MDA2OTcsInVzZXJuYW1lIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MTk4NzA5NywiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.jncnYlwUMSuC_NHE9g-5zoWTpcds7IoRwLgIQEcOIzxCgE4sw21QK3NsAssttEEYfMyEcK4N1tQBHpmGqf2oVg
Content-Type: application/json

{
  "content": "apple"
}


### GET
GET Localhost:7070/report/lget/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE5MDA2OTcsInVzZXJuYW1lIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MTk4NzA5NywiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.jncnYlwUMSuC_NHE9g-5zoWTpcds7IoRwLgIQEcOIzxCgE4sw21QK3NsAssttEEYfMyEcK4N1tQBHpmGqf2oVg

