GET Localhost:7070/getALL
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzIwODQ0MzEsInVzZXJuYW1lIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MjE3MDgzMSwiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.Z9S386iddNU7fQsPd8jqyyAAq2x8mEs52eUkDbUNxa93flQSq_qNElyFVLW9tHMEyfOG68IW1KXbvfvq9m1bew